export const chatOutput = document.querySelector(".chatHistory_messages");
export const chatInput = document.querySelector("#inputField");
export const charCount = document.querySelector("#charCount");
export const submitBtn = document.querySelector("#askButton");
export const inputField = document.querySelector("#inputField");
export const resetChatForm = document.querySelector("#newChatForm");
export const botName = "PizzaBot";
export const userName = "You";
export const defaultErrorMsg = "Oops, something went wrong. Please try again.";
